### ISSUE TITLE
[RFC] RAII executor/deallocator

### ISSUE THREAD

**Issue by amyspark** [bad-alloc-heavy-industries/substrate#22]
👋 

The WebP libraries rely on a pattern like [this](https://github.com/google/skia/blob/1c272f26a58732e56a7079098422dc3fd52f6434/include/private/SkTemplates.h#L59) and [this](https://invent.kde.org/graphics/krita/-/merge_requests/1468/diffs#1f62d05f446aab982783a2a6b136a7e612157c5f_103_120): having a RAII type that can allocate the destructor straight from a template parameter (instead of the type, and then a separate feeding), and that does *not* need to destroy the whole object, just some cache on its internal state.

Would it be possible to add such a primitive to substrate?

**Comment by dragonmux** [comment]
Looks like an interesting concept that should reduce the verboseness (and therefore chances for making mistakes) of such constructs quite usefully
