### ISSUE TITLE
CodeQL action deprecation

### ISSUE THREAD

**Issue by amyspark** [bad-alloc-heavy-industries/substrate#84]
https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/

codeql-action@v2 is used here, we should take action while spoons allow.

**Comment by dragonmux** [comment]
Ooo, agreed - looks like it's a pretty low-effort conversion at least! We're happy for you to PR a fix or us to write one and PR it - take your pick and we'll make it happen in the next couple of days.

**Comment by amyspark** [comment]
@dragonmux I can put a PR together tomorrow, if you'd like.

**Comment by dragonmux** [comment]
Yes please!
